In [31]:
import pandas as pd
import numpy as numpy


monthly_transactions= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\1_Mobile_Money_Monthly_Transactions_2015_2024.xlsx")
county_inclusion= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\2_County_Financial_Inclusion_2024.xlsx")
finaccess_historical= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\3_FinAccess_Historical_Survey_2006_2024.xlsx")
agent_network= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\4_Agent_Network_by_County.xlsx")
demographic_exclusion= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\5_Demographic_Exclusion_Analysis.xlsx")
annual_kpis= pd.read_excel(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Raw Data\6_Annual_KPIs_Summary.xlsx")

In [32]:
print(monthly_transactions.head())
print(county_inclusion.head())
print(finaccess_historical.head())
print(agent_network.head())
print(demographic_exclusion.head())
print(annual_kpis.head())

   Year  Month Month_Name  Active_Agents  Registered_Accounts_M  \
0  2015      1    January         131087                  25.21
1  2015      2   February         126547                  24.31
2  2015      3      March         128758                  24.71
3  2015      4      April         128608                  24.66
4  2015      5        May         132899                  25.46

   Active_Accounts_M  Txn_Volume_M  Txn_Value_KES_B  Avg_Txn_Size_KES  \
0              13.11         100.6           1270.5             12629
1              12.64          92.3           1165.8             12631
2              12.85          98.4           1243.0             12632
3              12.82          98.1           1239.1             12631
4              13.24          96.3           1217.0             12638

   Agent_CICO_Volume_M  Agent_CICO_Value_KES_B
0                 45.6                   512.5
1                 40.4                   453.0
2                 43.7                   490.5
3                 43.4                   487.4
4                 43.9                   493.7
    County_ID  County_Name Region  Formal_Inclusion_%  Exclusion_%  \
0     Mombasa            1  Coast               0.912        0.088
1       Kwale            2  Coast               0.715        0.285
2      Kilifi            3  Coast               0.743        0.257
3  Tana River            4  Coast               0.624        0.376
4        Lamu            5  Coast               0.791        0.209

   Mobile_Money_Usage_%  Informal_Only_%  Rural_Inclusion_%  \
0                 0.881            0.031              0.854
1                 0.652            0.063              0.684
2                 0.689            0.054              0.712
3                 0.558            0.066              0.583
4                 0.723            0.068              0.756

   Urban_Inclusion_%  Population_2024 High_Inclusion_Flag
0              0.923          1200000                 Yes
1              0.750           960000                  No
2              0.778          1453000                  No
3              0.670           315000                  No
4              0.830           143000                  No
   Survey_Year  Formal_Access_%  Formal_Access_Overall_%  Informal_Only_%  \
0         2006            0.267                    0.321            0.054
1         2009            0.404                    0.413            0.046
2         2013            0.667                    0.753            0.078
3         2016            0.753                    0.753            0.047
4         2019            0.829                    0.830            0.040

   Mobile_Money_%  Excluded_%             Context_Note  Banked_%  SACCO_%  \
0           0.073       0.675           Pre-M-Pesa era     0.140    0.018
1           0.140       0.541    M-Pesa early adoption     0.226    0.041
2           0.153       0.170   Mobile money expansion     0.420    0.090
3           0.147       0.174  Digital services growth     0.540    0.140
4           0.120       0.090  Agency banking maturity     0.630    0.160

   MFI_%  Insurance_%
0  0.005        0.002
1  0.015        0.008
2  0.040        0.030
3  0.055        0.050
4  0.050        0.070
  County_Name  County_ID       Region  Active_Agents_2024  Population_2024  \
0     Nairobi         47      Nairobi               62400          4397073
1     Mombasa          1        Coast               18200          1200000
2      Kiambu         22      Central               24300          2417000
3      Nakuru         32  Rift Valley               15800          2162000
4    Kakamega         37      Western               11200          1867000

   Agents_Per_10k_Pop  Agents_Per_1000_Adults Settlement_Type  \
0                14.2                     3.8           Urban
1                15.2                     1.2           Urban
2                10.1                     2.4      Peri-urban
3                 7.3                     1.8           Mixed
4                 6.0                     1.3           Rural

  Agent_Density_Tier
0               High
1               High
2               High
3             Medium
4             Medium
        Segment Category  Formal_Inclusion_%  Excluded_%  Mobile_Money_%  \
0          Male   Gender               0.857       0.083           0.835
1        Female   Gender               0.841       0.108           0.823
2   Youth 18-25      Age               0.724       0.276           0.701
3  Adults 26-35      Age               0.892       0.108           0.874
4  Adults 36-45      Age               0.885       0.115           0.859

   Bank_Account_%  SACCO_%  Est_Population_M  Excluded_Count_M  \
0           0.672    0.185              16.8              1.39
1           0.634    0.178              17.2              1.86
2           0.453    0.082               5.8              1.60
3           0.701    0.223               7.4              0.80
4           0.698    0.241               6.2              0.71

     Primary_Barrier     Data_Source
0         Low demand  FinAccess 2024
1   Lack of ID/phone  FinAccess 2024
2  No ID / no income  FinAccess 2024
3         Low income  FinAccess 2024
4      Documentation  FinAccess 2024
   Year  Total_Txn_Value_KES_B  YoY_Value_Growth_%  Total_Txn_Volume_M  \
0  2015                   1238                 NaN                1140
1  2016                   1512            0.221325                1320
2  2017                   1762            0.165344                1560
3  2018                   2132            0.209989                1800
4  2019                   2497            0.171201                2100

   YoY_Volume_Growth_%  Active_Agents  Registered_Accounts_M  \
0                  NaN         130000                   25.0
1             0.157895         155000                   28.0
2             0.181818         175000                   30.5
3             0.153846         195000                   33.0
4             0.166667         225000                   38.0

   Active_Accounts_M  Formal_Inclusion_%  GDP_KES_T  Mobile_Money_GDP_%
0                 13                 NaN        6.0            0.206333
1                 15                 NaN        6.5            0.232615
2                 17                 NaN        7.0            0.251714
3                 19                 NaN        7.7            0.276883
4                 22               0.829        8.5            0.293765

In [33]:
monthly_transactions.info()
county_inclusion.info()
finaccess_historical.info()
agent_network.info()
demographic_exclusion.info()
annual_kpis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    120 non-null    int64
 1   Month                   120 non-null    int64
 2   Month_Name              120 non-null    object
 3   Active_Agents           120 non-null    int64
 4   Registered_Accounts_M   120 non-null    float64
 5   Active_Accounts_M       120 non-null    float64
 6   Txn_Volume_M            120 non-null    float64
 7   Txn_Value_KES_B         120 non-null    float64
 8   Avg_Txn_Size_KES        120 non-null    int64
 9   Agent_CICO_Volume_M     120 non-null    float64
 10  Agent_CICO_Value_KES_B  120 non-null    float64
dtypes: float64(6), int64(4), object(1)
memory usage: 10.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   County_ID             47 non-null     object
 1   County_Name           47 non-null     int64
 2   Region                47 non-null     object
 3   Formal_Inclusion_%    47 non-null     float64
 4   Exclusion_%           47 non-null     float64
 5   Mobile_Money_Usage_%  47 non-null     float64
 6   Informal_Only_%       47 non-null     float64
 7   Rural_Inclusion_%     47 non-null     float64
 8   Urban_Inclusion_%     47 non-null     float64
 9   Population_2024       47 non-null     int64
 10  High_Inclusion_Flag   47 non-null     object
dtypes: float64(6), int64(2), object(3)
memory usage: 4.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survey_Year              7 non-null      int64
 1   Formal_Access_%          7 non-null      float64
 2   Formal_Access_Overall_%  7 non-null      float64
 3   Informal_Only_%          7 non-null      float64
 4   Mobile_Money_%           7 non-null      float64
 5   Excluded_%               7 non-null      float64
 6   Context_Note             7 non-null      object
 7   Banked_%                 7 non-null      float64
 8   SACCO_%                  7 non-null      float64
 9   MFI_%                    7 non-null      float64
 10  Insurance_%              7 non-null      float64
dtypes: float64(9), int64(1), object(1)
memory usage: 748.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   County_Name             47 non-null     object
 1   County_ID               47 non-null     int64
 2   Region                  47 non-null     object
 3   Active_Agents_2024      47 non-null     int64
 4   Population_2024         47 non-null     int64
 5   Agents_Per_10k_Pop      47 non-null     float64
 6   Agents_Per_1000_Adults  47 non-null     float64
 7   Settlement_Type         47 non-null     object
 8   Agent_Density_Tier      47 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 3.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Segment             20 non-null     object
 1   Category            20 non-null     object
 2   Formal_Inclusion_%  20 non-null     float64
 3   Excluded_%          20 non-null     float64
 4   Mobile_Money_%      20 non-null     float64
 5   Bank_Account_%      20 non-null     float64
 6   SACCO_%             20 non-null     float64
 7   Est_Population_M    20 non-null     float64
 8   Excluded_Count_M    20 non-null     float64
 9   Primary_Barrier     20 non-null     object
 10  Data_Source         20 non-null     object
dtypes: float64(7), object(4)
memory usage: 1.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   10 non-null     int64
 1   Total_Txn_Value_KES_B  10 non-null     int64
 2   YoY_Value_Growth_%     9 non-null      float64
 3   Total_Txn_Volume_M     10 non-null     int64
 4   YoY_Volume_Growth_%    9 non-null      float64
 5   Active_Agents          10 non-null     int64
 6   Registered_Accounts_M  10 non-null     float64
 7   Active_Accounts_M      10 non-null     int64
 8   Formal_Inclusion_%     3 non-null      float64
 9   GDP_KES_T              10 non-null     float64
 10  Mobile_Money_GDP_%     10 non-null     float64
dtypes: float64(6), int64(5)
memory usage: 1012.0 bytes

In [34]:
monthly_transactions.columns= monthly_transactions.columns.str.lower()
county_inclusion.columns= county_inclusion.columns.str.lower()
finaccess_historical.columns= finaccess_historical.columns.str.lower()
agent_network.columns= agent_network.columns.str.lower()
demographic_exclusion.columns= demographic_exclusion.columns.str.lower()
annual_kpis.columns= annual_kpis.columns.str.lower()

In [35]:
monthly_transactions['month_name']= monthly_transactions['month_name'].str.strip()
print(monthly_transactions['month_name'])

0        January
1       February
2          March
3          April
4            May
         ...
115       August
116    September
117      October
118     November
119     December
Name: month_name, Length: 120, dtype: object

In [36]:
print(monthly_transactions[['year', 'month', 'month_name']].head(30))

    year  month month_name
0   2015      1    January
1   2015      2   February
2   2015      3      March
3   2015      4      April
4   2015      5        May
5   2015      6       June
6   2015      7       July
7   2015      8     August
8   2015      9  September
9   2015     10    October
10  2015     11   November
11  2015     12   December
12  2016      1    January
13  2016      2   February
14  2016      3      March
15  2016      4      April
16  2016      5        May
17  2016      6       June
18  2016      7       July
19  2016      8     August
20  2016      9  September
21  2016     10    October
22  2016     11   November
23  2016     12   December
24  2017      1    January
25  2017      2   February
26  2017      3      March
27  2017      4      April
28  2017      5        May
29  2017      6       June

In [37]:
monthly_transactions.describe()

,year,month,active_agents,registered_accounts_m,active_accounts_m,txn_volume_m,txn_value_kes_b,avg_txn_size_kes,agent_cico_volume_m,agent_cico_value_kes_b
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,2019.500000,6.500000,255804.958333,49.251917,27.043667,185.993333,2925.489167,15321.216667,83.705833,1170.080000
std,2.884324,3.466527,88390.586345,20.604965,11.310035,62.013037,1929.448493,6220.557221,28.221073,774.931104
min,2015.000000,1.000000,126547.000000,24.310000,12.640000,91.200000,675.500000,2589.000000,40.400000,265.000000
25%,2017.000000,3.750000,179102.500000,30.907500,17.227500,132.475000,1459.425000,13076.000000,58.725000,574.100000
50%,2019.500000,6.500000,244720.500000,43.085000,24.070000,183.800000,2198.950000,13381.000000,82.200000,889.650000
75%,2022.000000,9.250000,339019.000000,67.752500,36.867500,239.625000,4216.950000,19998.000000,107.650000,1693.575000
max,2024.000000,12.000000,395117.000000,84.950000,47.420000,300.600000,7352.500000,26158.000000,138.300000,3028.500000

In [38]:
print(monthly_transactions.isna().sum())
print(county_inclusion.isna().sum())
print(finaccess_historical.isna().sum())
print(agent_network.isna().sum())
print(demographic_exclusion.isna().sum())
print(annual_kpis.isna().sum())

year                      0
month                     0
month_name                0
active_agents             0
registered_accounts_m     0
active_accounts_m         0
txn_volume_m              0
txn_value_kes_b           0
avg_txn_size_kes          0
agent_cico_volume_m       0
agent_cico_value_kes_b    0
dtype: int64
county_id               0
county_name             0
region                  0
formal_inclusion_%      0
exclusion_%             0
mobile_money_usage_%    0
informal_only_%         0
rural_inclusion_%       0
urban_inclusion_%       0
population_2024         0
high_inclusion_flag     0
dtype: int64
survey_year                0
formal_access_%            0
formal_access_overall_%    0
informal_only_%            0
mobile_money_%             0
excluded_%                 0
context_note               0
banked_%                   0
sacco_%                    0
mfi_%                      0
insurance_%                0
dtype: int64
county_name               0
county_id                 0
region                    0
active_agents_2024        0
population_2024           0
agents_per_10k_pop        0
agents_per_1000_adults    0
settlement_type           0
agent_density_tier        0
dtype: int64
segment               0
category              0
formal_inclusion_%    0
excluded_%            0
mobile_money_%        0
bank_account_%        0
sacco_%               0
est_population_m      0
excluded_count_m      0
primary_barrier       0
data_source           0
dtype: int64
year                     0
total_txn_value_kes_b    0
yoy_value_growth_%       1
total_txn_volume_m       0
yoy_volume_growth_%      1
active_agents            0
registered_accounts_m    0
active_accounts_m        0
formal_inclusion_%       7
gdp_kes_t                0
mobile_money_gdp_%       0
dtype: int64

## County Inclusion

In [39]:
county_inclusion.head()

,county_id,county_name,region,formal_inclusion_%,exclusion_%,mobile_money_usage_%,informal_only_%,rural_inclusion_%,urban_inclusion_%,population_2024,high_inclusion_flag
0,Mombasa,1,Coast,0.912,0.088,0.881,0.031,0.854,0.923,1200000,Yes
1,Kwale,2,Coast,0.715,0.285,0.652,0.063,0.684,0.750,960000,No
2,Kilifi,3,Coast,0.743,0.257,0.689,0.054,0.712,0.778,1453000,No
3,Tana River,4,Coast,0.624,0.376,0.558,0.066,0.583,0.670,315000,No
4,Lamu,5,Coast,0.791,0.209,0.723,0.068,0.756,0.830,143000,No

In [40]:
county_inclusion= county_inclusion.rename(columns={'county_id': 'county_name', 
                                                   'county_name': 'county_id',
                                                   'formal_inclusion_%': 'formal_inclusion_pct',
                                                   'exclusion_%' : 'exclusion_pct',
                                                   'mobile_money_usage_%': 'mobile_money_usage_pct',
                                                   'informal_only_%' : 'informal_only_pct',
                                                    'rural_inclusion_%': 'rural_inclusion_pct',
                                                    'urban_inclusion_%' : 'urban_inclusion_pct'})
county_inclusion= pd.DataFrame(county_inclusion)
print(county_inclusion)

        county_name  county_id         region  formal_inclusion_pct  \
0           Mombasa          1          Coast                 0.912
1             Kwale          2          Coast                 0.715
2            Kilifi          3          Coast                 0.743
3        Tana River          4          Coast                 0.624
4              Lamu          5          Coast                 0.791
5      Taita Taveta          6          Coast                 0.812
6           Garissa          7  North Eastern                 0.784
7             Wajir          8  North Eastern                 0.653
8           Mandera          9  North Eastern                 0.875
9          Marsabit         10        Eastern                 0.668
10           Isiolo         11        Eastern                 0.894
11             Meru         12        Eastern                 0.867
12    Tharaka Nithi         13        Eastern                 0.823
13             Embu         14        Eastern                 0.856
14            Kitui         15        Eastern                 0.769
15         Machakos         16        Eastern                 0.845
16          Makueni         17        Eastern                 0.801
17        Nyandarua         18        Central                 0.974
18            Nyeri         19        Central                 0.938
19        Kirinyaga         20        Central                 0.941
20         Murang'a         21        Central                 0.884
21           Kiambu         22        Central                 0.940
22          Turkana         23    Rift Valley                 0.685
23       West Pokot         24    Rift Valley                 0.730
24          Samburu         25    Rift Valley                 0.796
25      Trans Nzoia         26    Rift Valley                 0.790
26      Uasin Gishu         27    Rift Valley                 0.886
27  Elgeyo Marakwet         28    Rift Valley                 0.805
28            Nandi         29    Rift Valley                 0.831
29          Baringo         30    Rift Valley                 0.784
30         Laikipia         31    Rift Valley                 0.843
31           Nakuru         32    Rift Valley                 0.893
32            Narok         33    Rift Valley                 0.752
33          Kajiado         34    Rift Valley                 0.876
34          Kericho         35    Rift Valley                 0.854
35            Bomet         36    Rift Valley                 0.808
36         Kakamega         37        Western                 0.806
37           Vihiga         38        Western                 0.852
38          Bungoma         39        Western                 0.814
39            Busia         40        Western                 0.763
40            Siaya         41         Nyanza                 0.805
41           Kisumu         42         Nyanza                 0.879
42         Homa Bay         43         Nyanza                 0.786
43           Migori         44         Nyanza                 0.774
44            Kisii         45         Nyanza                 0.837
45          Nyamira         46         Nyanza                 0.821
46          Nairobi         47        Nairobi                 0.925

    exclusion_pct  mobile_money_usage_pct  informal_only_pct  \
0           0.088                   0.881              0.031
1           0.285                   0.652              0.063
2           0.257                   0.689              0.054
3           0.376                   0.558              0.066
4           0.209                   0.723              0.068
5           0.188                   0.754              0.058
6           0.216                   0.731              0.053
7           0.347                   0.587              0.066
8           0.125                   0.823              0.052
9           0.332                   0.601              0.067
10          0.106                   0.842              0.052
11          0.133                   0.815              0.052
12          0.177                   0.768              0.055
13          0.144                   0.801              0.055
14          0.231                   0.712              0.057
15          0.155                   0.790              0.055
16          0.199                   0.745              0.056
17          0.026                   0.938              0.036
18          0.062                   0.901              0.037
19          0.059                   0.904              0.037
20          0.116                   0.837              0.047
21          0.060                   0.912              0.028
22          0.315                   0.621              0.064
23          0.270                   0.665              0.065
24          0.204                   0.738              0.058
25          0.210                   0.735              0.055
26          0.114                   0.839              0.047
27          0.195                   0.750              0.055
28          0.169                   0.776              0.055
29          0.216                   0.729              0.055
30          0.157                   0.790              0.053
31          0.107                   0.848              0.045
32          0.248                   0.689              0.063
33          0.124                   0.829              0.047
34          0.146                   0.801              0.053
35          0.192                   0.753              0.055
36          0.194                   0.751              0.055
37          0.148                   0.798              0.054
38          0.186                   0.760              0.054
39          0.237                   0.708              0.055
40          0.195                   0.750              0.055
41          0.121                   0.832              0.047
42          0.214                   0.731              0.055
43          0.226                   0.719              0.055
44          0.163                   0.782              0.055
45          0.179                   0.766              0.055
46          0.075                   0.898              0.027

    rural_inclusion_pct  urban_inclusion_pct  population_2024  \
0                 0.854                0.923          1200000
1                 0.684                0.750           960000
2                 0.712                0.778          1453000
3                 0.583                0.670           315000
4                 0.756                0.830           143000
5                 0.779                0.848           340000
6                 0.750                0.820           841000
7                 0.614                0.695           781000
8                 0.840                0.912           867000
9                 0.625                0.714           459000
10                0.860                0.929           268000
11                0.832                0.904          1545000
12                0.785                0.863           393000
13                0.818                0.896           608000
14                0.730                0.811          1136000
15                0.806                0.885          1421000
16                0.762                0.842           987000
17                0.952                0.997           638000
18                0.915                0.963           759000
19                0.918                0.965           610000
20                0.850                0.919          1056000
21                0.925                0.956          2417000
22                0.645                0.727           926000
23                0.691                0.771           621000
24                0.755                0.839           223000
25                0.752                0.829           990000
26                0.851                0.922          1163000
27                0.768                0.844           454000
28                0.790                0.873           885000
29                0.745                0.825           666000
30                0.805                0.883           518000
31                0.862                0.925          2162000
32                0.710                0.795          1157000
33                0.842                0.912          1117000
34                0.815                0.894           947000
35                0.770                0.847           876000
36                0.768                0.845          1867000
37                0.810                0.895           590000
38                0.775                0.854          1670000
39                0.725                0.802           893000
40                0.768                0.844           993000
41                0.847                0.913          1155000
42                0.748                0.825          1131000
43                0.735                0.815          1145000
44                0.798                0.877          1267000
45                0.780                0.863           605000
46                0.910                0.941          4397000

   high_inclusion_flag
0                  Yes
1                   No
2                   No
3                   No
4                   No
5                   No
6                   No
7                   No
8                   No
9                   No
10                 Yes
11                 Yes
12                  No
13                 Yes
14                  No
15                 Yes
16                  No
17                 Yes
18                 Yes
19                 Yes
20                 Yes
21                 Yes
22                  No
23                  No
24                  No
25                  No
26                 Yes
27                  No
28                  No
29                  No
30                 Yes
31                 Yes
32                  No
33                 Yes
34                 Yes
35                  No
36                  No
37                 Yes
38                  No
39                  No
40                  No
41                 Yes
42                  No
43                  No
44                  No
45                  No
46                 Yes

In [42]:
county_inclusion['county_id']= county_inclusion['county_id'].astype(int)
county_inclusion['county_name']= county_inclusion['county_name'].astype(str)


print(county_inclusion.head())

  county_name  county_id region  formal_inclusion_pct  exclusion_pct  \
0     Mombasa          1  Coast                 0.912          0.088
1       Kwale          2  Coast                 0.715          0.285
2      Kilifi          3  Coast                 0.743          0.257
3  Tana River          4  Coast                 0.624          0.376
4        Lamu          5  Coast                 0.791          0.209

   mobile_money_usage_pct  informal_only_pct  rural_inclusion_pct  \
0                   0.881              0.031                0.854
1                   0.652              0.063                0.684
2                   0.689              0.054                0.712
3                   0.558              0.066                0.583
4                   0.723              0.068                0.756

   urban_inclusion_pct  population_2024 high_inclusion_flag
0                0.923          1200000                 Yes
1                0.750           960000                  No
2                0.778          1453000                  No
3                0.670           315000                  No
4                0.830           143000                  No

In [43]:
county_inclusion['county_name'].sort_values().unique()

array(['Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo Marakwet', 'Embu',
       'Garissa', 'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho',
       'Kiambu', 'Kilifi', 'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui',
       'Kwale', 'Laikipia', 'Lamu', 'Machakos', 'Makueni', 'Mandera',
       'Marsabit', 'Meru', 'Migori', 'Mombasa', "Murang'a", 'Nairobi',
       'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua', 'Nyeri',
       'Samburu', 'Siaya', 'Taita Taveta', 'Tana River', 'Tharaka Nithi',
       'Trans Nzoia', 'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir',
       'West Pokot'], dtype=object)

In [44]:
print(finaccess_historical.head())

   survey_year  formal_access_%  formal_access_overall_%  informal_only_%  \
0         2006            0.267                    0.321            0.054
1         2009            0.404                    0.413            0.046
2         2013            0.667                    0.753            0.078
3         2016            0.753                    0.753            0.047
4         2019            0.829                    0.830            0.040

   mobile_money_%  excluded_%             context_note  banked_%  sacco_%  \
0           0.073       0.675           Pre-M-Pesa era     0.140    0.018
1           0.140       0.541    M-Pesa early adoption     0.226    0.041
2           0.153       0.170   Mobile money expansion     0.420    0.090
3           0.147       0.174  Digital services growth     0.540    0.140
4           0.120       0.090  Agency banking maturity     0.630    0.160

   mfi_%  insurance_%
0  0.005        0.002
1  0.015        0.008
2  0.040        0.030
3  0.055        0.050
4  0.050        0.070

In [46]:
finaccess_historical["survey_year"].unique()

array([2006, 2009, 2013, 2016, 2019, 2021, 2024])

In [48]:
finaccess_historical = finaccess_historical.rename(columns={
    "formal_access_%"  : "formal_access_pct",
    "formal_access_overall_%" : "formal_access_overall_pct",
    "informal_only_%"  : "informal_only_pct",
    "mobile_money_%"  : "mobile_money_pct",
    "excluded_%"  : "excluded_pct",
    "banked_%"  : "banked_pct",
    "sacco_%"  : "sacco_pct",
    "mfi_%"  : "mfi_pct",
    "insurance_%"  : "insurance_pct",
})
finaccess_historical= pd.DataFrame(finaccess_historical)

In [49]:
print(agent_network.head())

  county_name  county_id       region  active_agents_2024  population_2024  \
0     Nairobi         47      Nairobi               62400          4397073
1     Mombasa          1        Coast               18200          1200000
2      Kiambu         22      Central               24300          2417000
3      Nakuru         32  Rift Valley               15800          2162000
4    Kakamega         37      Western               11200          1867000

   agents_per_10k_pop  agents_per_1000_adults settlement_type  \
0                14.2                     3.8           Urban
1                15.2                     1.2           Urban
2                10.1                     2.4      Peri-urban
3                 7.3                     1.8           Mixed
4                 6.0                     1.3           Rural

  agent_density_tier
0               High
1               High
2               High
3             Medium
4             Medium

In [52]:
# Fix — add the two missing counties
mandera_turkana = pd.DataFrame([
    {
        "county_name"       : "Mandera",
        "county_id"         : 9,
        "region"            : "North Eastern",
        "active_agents_2024": 1900,
        "population_2024"   : 867000,
        "settlement_type"   : "Rural",
    },
    {
        "county_name"       : "Turkana",
        "county_id"         : 23,
        "region"            : "Rift Valley",
        "active_agents_2024": 2600,
        "population_2024"   : 926000,
        "settlement_type"   : "Rural",
    },
])


agent_network = pd.concat([agent_network, mandera_turkana], ignore_index=True)
agent_network = agent_network.sort_values("county_id").reset_index(drop=True)

In [53]:
# Fix 1 — correct formula: agents / population × 1,000
agent_network["agents_per_10k_pop"] = (
    agent_network["active_agents_2024"] / agent_network["population_2024"] * 1000
).round(2)

In [54]:
# Also recompute agents_per_1000_adults (adults ≈ 55% of population)
agent_network["agents_per_1000_adults"] = (
    agent_network["active_agents_2024"] / (agent_network["population_2024"] * 0.55) * 1000
).round(2)

In [55]:
print(agent_network.head())

  county_name  county_id region  active_agents_2024  population_2024  \
0     Mombasa          1  Coast               18200          1200000
1       Kwale          2  Coast                4800           960000
2      Kilifi          3  Coast                7200          1453000
3  Tana River          4  Coast                1700           315000
4        Lamu          5  Coast                1600           143000

   agents_per_10k_pop  agents_per_1000_adults settlement_type  \
0               15.17                   27.58           Urban
1                5.00                    9.09           Rural
2                4.96                    9.01           Rural
3                5.40                    9.81           Rural
4               11.19                   20.34           Mixed

  agent_density_tier
0               High
1                Low
2                Low
3                Low
4               High

In [56]:
# Fix 2 — rederive tier from corrected density values
def density_tier(x):
    if x >= 10:  return "High"
    elif x >= 6: return "Medium"
    else:        return "Low"
 
agent_network["agent_density_tier"] = agent_network["agents_per_10k_pop"].apply(density_tier)

In [57]:
# Remove duplicates
agent_network= agent_network.drop_duplicates(subset= ['county_name', 'county_id'])

In [58]:
print(agent_network.count())

county_name               47
county_id                 47
region                    47
active_agents_2024        47
population_2024           47
agents_per_10k_pop        47
agents_per_1000_adults    47
settlement_type           47
agent_density_tier        47
dtype: int64

In [59]:
print(demographic_exclusion.head())

        segment category  formal_inclusion_%  excluded_%  mobile_money_%  \
0          Male   Gender               0.857       0.083           0.835
1        Female   Gender               0.841       0.108           0.823
2   Youth 18-25      Age               0.724       0.276           0.701
3  Adults 26-35      Age               0.892       0.108           0.874
4  Adults 36-45      Age               0.885       0.115           0.859

   bank_account_%  sacco_%  est_population_m  excluded_count_m  \
0           0.672    0.185              16.8              1.39
1           0.634    0.178              17.2              1.86
2           0.453    0.082               5.8              1.60
3           0.701    0.223               7.4              0.80
4           0.698    0.241               6.2              0.71

     primary_barrier     data_source
0         Low demand  FinAccess 2024
1   Lack of ID/phone  FinAccess 2024
2  No ID / no income  FinAccess 2024
3         Low income  FinAccess 2024
4      Documentation  FinAccess 2024

In [61]:
# Fix — rename % columns
demographic_exclusion = demographic_exclusion.rename(columns={
    "formal_inclusion_%"  : "formal_inclusion_pct",
    "excluded_%" : "excluded_pct",
    "mobile_money_%"  : "mobile_money_pct",
    "bank_account_%"  : "bank_account_pct",
    "sacco_%"  : "sacco_pct"
})
demographic_exclusion= pd.DataFrame(demographic_exclusion)

In [62]:
print(annual_kpis.head())

   year  total_txn_value_kes_b  yoy_value_growth_%  total_txn_volume_m  \
0  2015                   1238                 NaN                1140
1  2016                   1512            0.221325                1320
2  2017                   1762            0.165344                1560
3  2018                   2132            0.209989                1800
4  2019                   2497            0.171201                2100

   yoy_volume_growth_%  active_agents  registered_accounts_m  \
0                  NaN         130000                   25.0
1             0.157895         155000                   28.0
2             0.181818         175000                   30.5
3             0.153846         195000                   33.0
4             0.166667         225000                   38.0

   active_accounts_m  formal_inclusion_%  gdp_kes_t  mobile_money_gdp_%
0                 13                 NaN        6.0            0.206333
1                 15                 NaN        6.5            0.232615
2                 17                 NaN        7.0            0.251714
3                 19                 NaN        7.7            0.276883
4                 22               0.829        8.5            0.293765

In [64]:
# Fix — rename % columns
annual_kpis = annual_kpis.rename(columns={
    "yoy_value_growth_%"  : "yoy_value_growth_pct",
    "yoy_volume_growth_%" : "yoy_volume_growth_pct",
    "formal_inclusion_%"  : "formal_inclusion_pct",
    "mobile_money_gdp_%"  : "mobile_money_gdp_pct",
})
annual_kpis= pd.DataFrame(annual_kpis)

In [65]:
annual_kpis["yoy_value_growth_pct"]  = annual_kpis["yoy_value_growth_pct"].fillna(0.0)
annual_kpis["yoy_volume_growth_pct"] = annual_kpis["yoy_volume_growth_pct"].fillna(0.0)
print(annual_kpis[["yoy_value_growth_pct","yoy_volume_growth_pct"]])

   yoy_value_growth_pct  yoy_volume_growth_pct
0              0.000000               0.000000
1              0.221325               0.157895
2              0.165344               0.181818
3              0.209989               0.153846
4              0.171201               0.166667
5              0.410092               0.114286
6              0.342232               0.076923
7              0.229793               0.142857
8              0.178252               0.083333
9              0.270444               0.076923

In [67]:
# Fix — interpolate the 7 missing years
# formal_inclusion_pct only has values for survey years: 2019, 2021, 2024
# Linear interpolation fills the gaps for trend charts
# The original NaN values are preserved; a new column holds the filled version
annual_kpis = annual_kpis.sort_values("year").reset_index(drop=True)
 
annual_kpis["formal_inclusion_pct_interp"] = (
    annual_kpis["formal_inclusion_pct"]
    .interpolate(method="linear", limit_direction="both")
    .round(4)
)

## Save cleaned datasets

In [69]:
monthly_transactions.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_Mobile_Money_Monthly_Transactions_2015_2024.csv", index=False)
county_inclusion.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_County_Financial_Inclusion_2024.csv", index=False)
finaccess_historical.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_FinAccess_Historical_Survey_2006_2024.csv", index=False)
agent_network.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_Agent_Network_by_County.csv", index=False)
demographic_exclusion.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_Demographic_Exclusion_Analysis.csv", index=False)
annual_kpis.to_csv(r"C:\MY DOCUMENTS\Financial_Inclusion_Kenya\Data\Clean Data\c_Annual_KPIs_Summary.csv", index=False)